# Generated by Django 5.2 on 2026-07-19 18:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0010_remove_stock_and_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('shipping_address', models.JSONField()),
                ('billing_address', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending (Awaiting Payment)'), ('PROCESSING', 'Processing (Paid)'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('vendor_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vendor_shipping', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vendor_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('vendor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='orders.order')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_orders', to='shops.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('variant_attributes', models.JSONField(blank=True, default=dict)),
                ('shop_name', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('item_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='shops.productvariant')),
                ('vendor_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.vendororder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
