# Generated by Django 5.2 on 2026-07-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
        ('shops', '0012_alter_product_status_alter_shop_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Awaiting Payment)'), ('PROCESSING', 'Processing (Paid)'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='vendororder',
            constraint=models.UniqueConstraint(fields=('order', 'shop'), name='unique_vendor_order_per_shop'),
        ),
    ]
