# Generated by Django 5.2 on 2026-07-21 01:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_alter_vendororder_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('status', models.CharField(choices=[('REQUESTED', 'Return Requested'), ('APPROVED', 'Return Approved'), ('SHIPPED', 'Item Shipped Back'), ('RECEIVED', 'Item Received by Vendor'), ('REJECTED', 'Return Rejected')], default='REQUESTED', max_length=20)),
                ('reason', models.TextField()),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('vendor_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.vendororder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.return')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
