# Generated by Django 5.2 on 2026-07-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_return_returnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('COMPLETED', 'Completed'), ('PARTIALLY_RETURNED', 'Partially Returned'), ('RETURNED', 'Returned')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Return Requested'), ('APPROVED', 'Return Approved'), ('SHIPPED', 'Item Shipped Back'), ('RECEIVED', 'Item Received by Vendor'), ('REJECTED', 'Return Rejected')], db_index=True, default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Awaiting Payment)'), ('PROCESSING', 'Processing (Paid)'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_RETURNED', 'Partially Returned'), ('RETURNED', 'Returned')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
