# Generated by Django 5.2 on 2026-07-25 19:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_alter_return_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('VENDOR_REVIEW', 'Vendor Review'), ('ESCALATED', 'Escalated to Administration'), ('ADMIN_REVIEW', 'Admin Review'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20)),
                ('reason', models.TextField()),
                ('outcome', models.CharField(blank=True, choices=[('CUSTOMER_FAVOUR', 'Customer Favour'), ('VENDOR_FAVOUR', 'Vendor Favour'), ('MUTUAL_SETTLEMENT', 'Mutual Settlement'), ('ADMIN_OVERRIDE', 'Admin Override'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('vendor_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='orders.vendororder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
