# Generated by Django 5.2 on 2026-07-11 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('image', models.ImageField(upload_to='products/')),
                ('sort_order', models.PositiveSmallIntegerField(default=1, help_text='Display order of the image. The image with the lowest sort_order is treated as the primary image.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shops.product')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
