# Generated by Django 5.2 on 2026-07-19 07:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('image', models.ImageField(upload_to='variants/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shops.productvariant')),
            ],
            options={
                'ordering': ('display_order', 'created_at'),
            },
        ),
    ]
