# Generated by Django 5.2 on 2026-07-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_migrate_variant_stock'),
        ('shops', '0009_variantimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
    ]
