# Generated by Django 5.2 on 2026-07-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_remove_stock_and_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shop',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='shop',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
