# Generated by Django 5.2 on 2026-07-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_productimage_unique_primary_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
    ]
