# Generated by Django 5.2 on 2026-07-21 01:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_alter_vendororder_status_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason_code', models.CharField(choices=[('CUSTOMER_REQUEST', 'Customer Request'), ('ADMIN_DECISION', 'Admin Decision'), ('DISPUTE_RESOLUTION', 'Dispute Resolution'), ('FRAUD', 'Fraud'), ('DUPLICATE_PAYMENT', 'Duplicate Payment'), ('OTHER', 'Other')], max_length=50)),
                ('admin_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Gateway Processing'), ('SUCCEEDED', 'Refund Succeeded'), ('FAILED', 'Refund Failed')], default='PENDING', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('vendor_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='orders.vendororder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
