# Generated by Django 5.2

from django.db import migrations


def migrate_stock_forward(apps, schema_editor):
    ProductVariant = apps.get_model("shops", "ProductVariant")
    Inventory = apps.get_model("inventory", "Inventory")

    inventories = []
    for variant in ProductVariant.objects.all():
        inventories.append(
            Inventory(
                variant=variant,
                quantity_on_hand=variant.stock
            )
        )
    Inventory.objects.bulk_create(inventories)


def migrate_stock_backward(apps, schema_editor):
    ProductVariant = apps.get_model("shops", "ProductVariant")
    Inventory = apps.get_model("inventory", "Inventory")

    for inventory in Inventory.objects.all():
        variant = inventory.variant
        variant.stock = inventory.quantity_on_hand
        variant.save(update_fields=["stock"])

    Inventory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('shops', '0009_variantimage'), # We assume this dependency allows access to variant.stock
    ]

    operations = [
        migrations.RunPython(migrate_stock_forward, migrate_stock_backward),
    ]
