# Generated by Django 5.2 on 2026-07-20 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SUSPEND', 'Suspend'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REFUND', 'Refund'), ('OTHER', 'Other')], max_length=50)),
                ('resource_type', models.CharField(help_text="The type of resource modified (e.g., 'Shop', 'Product')", max_length=100)),
                ('resource_id', models.CharField(help_text='The ID of the modified resource', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('before_state', models.JSONField(blank=True, help_text='JSON representation of the resource before modification', null=True)),
                ('after_state', models.JSONField(blank=True, help_text='JSON representation of the resource after modification', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='Optional reason or comment provided by the staff user', null=True)),
                ('actor', models.ForeignKey(help_text='The staff user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('can_read_platform', 'Can read platform configuration'), ('can_write_platform', 'Can write platform configuration'), ('can_read_rbac', 'Can read staff roles and permissions'), ('can_write_rbac', 'Can write staff roles and permissions'), ('can_read_vendors', 'Can read vendor administration'), ('can_write_vendors', 'Can write vendor administration'), ('can_read_products', 'Can read product moderation'), ('can_write_products', 'Can write product moderation'), ('can_read_orders', 'Can read order administration'), ('can_write_orders', 'Can write order administration'), ('can_read_finance', 'Can read financial administration'), ('can_write_finance', 'Can write financial administration')],
            },
        ),
    ]
