# Generated by Django 5.2 on 2026-07-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_adminauditlog_options_adminauditlog_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('can_manage_feature_flags', 'Can manage feature flags')],
            },
        ),
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('MARKETPLACE', 'Marketplace'), ('ORDERS', 'Orders'), ('PAYMENTS', 'Payments'), ('SHIPPING', 'Shipping'), ('PROMOTIONS', 'Promotions'), ('NOTIFICATIONS', 'Notifications'), ('SECURITY', 'Security'), ('ANALYTICS', 'Analytics'), ('SYSTEM', 'System')], max_length=50)),
                ('value_type', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('INTEGER', 'Integer'), ('DECIMAL', 'Decimal'), ('STRING', 'String'), ('JSON', 'JSON')], max_length=20)),
                ('value', models.JSONField(help_text='Stored as JSON internally to support exact typing.')),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('can_manage_platform_settings', 'Can manage platform configuration')],
            },
        ),
    ]
