# Generated by Django 5.2 on 2026-07-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_featureflag_platformsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System settings cannot be modified by staff.'),
        ),
    ]
