# Generated by Django 5.2 on 2026-07-20 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_platformsetting_is_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminauditlog',
            options={'ordering': ['-timestamp'], 'permissions': [('can_approve_vendor', 'Can approve a vendor shop'), ('can_reject_vendor', 'Can reject a vendor shop'), ('can_suspend_vendor', 'Can suspend a vendor shop'), ('can_restore_vendor', 'Can restore a vendor shop'), ('can_force_refund', 'Can force a refund on an order'), ('can_manage_platform_settings', 'Can manage platform configuration'), ('can_moderate_products', 'Can moderate products'), ('can_moderate_reviews', 'Can moderate reviews'), ('can_read_audit_logs', 'Can read audit logs')]},
        ),
    ]
