# Generated by Django 5.2 on 2026-07-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tracking_url',
            field=models.URLField(blank=True),
        ),
    ]
