# Generated by Django 5.2 on 2026-07-20 21:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0011_product_average_rating_product_review_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVelocityRollup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('ALL_TIME', 'All Time')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velocity_rollups', to='shops.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_velocity_rollups', to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'period', 'date'], name='analytics_p_shop_id_24e75a_idx'), models.Index(fields=['period', 'date', 'units_sold'], name='analytics_p_period_c6228a_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'period', 'date'), name='unique_product_velocity_period_date')],
            },
        ),
        migrations.CreateModel(
            name='ShopMetricRollup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('ALL_TIME', 'All Time')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('cancellation_count', models.PositiveIntegerField(default=0)),
                ('return_count', models.PositiveIntegerField(default=0)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('new_customers_count', models.PositiveIntegerField(default=0)),
                ('returning_customers_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_rollups', to='shops.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['shop', 'period', 'date'], name='analytics_s_shop_id_f88edb_idx')],
                'constraints': [models.UniqueConstraint(fields=('shop', 'period', 'date'), name='unique_shop_metric_period_date')],
            },
        ),
    ]
