# Generated by Django 5.2 on 2026-07-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('shops', '0011_product_average_rating_product_review_count_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productvelocityrollup',
            name='unique_product_velocity_period_date',
        ),
        migrations.RemoveConstraint(
            model_name='shopmetricrollup',
            name='unique_shop_metric_period_date',
        ),
        migrations.RemoveIndex(
            model_name='productvelocityrollup',
            name='analytics_p_shop_id_24e75a_idx',
        ),
        migrations.RemoveIndex(
            model_name='productvelocityrollup',
            name='analytics_p_period_c6228a_idx',
        ),
        migrations.RemoveIndex(
            model_name='shopmetricrollup',
            name='analytics_s_shop_id_f88edb_idx',
        ),
        migrations.RemoveField(
            model_name='productvelocityrollup',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shopmetricrollup',
            name='date',
        ),
        migrations.AddField(
            model_name='productvelocityrollup',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvelocityrollup',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvelocityrollup',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shopmetricrollup',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopmetricrollup',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopmetricrollup',
            name='schema_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='productvelocityrollup',
            index=models.Index(fields=['shop', 'period', 'period_start', 'period_end'], name='analytics_p_shop_id_39587d_idx'),
        ),
        migrations.AddIndex(
            model_name='productvelocityrollup',
            index=models.Index(fields=['period', 'period_start', 'period_end', 'units_sold'], name='analytics_p_period_ba9f02_idx'),
        ),
        migrations.AddIndex(
            model_name='shopmetricrollup',
            index=models.Index(fields=['shop', 'period', 'period_start', 'period_end'], name='analytics_s_shop_id_309196_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvelocityrollup',
            constraint=models.UniqueConstraint(fields=('product', 'period', 'period_start', 'period_end'), name='unique_product_velocity_period_boundaries'),
        ),
        migrations.AddConstraint(
            model_name='shopmetricrollup',
            constraint=models.UniqueConstraint(fields=('shop', 'period', 'period_start', 'period_end'), name='unique_shop_metric_period_boundaries'),
        ),
    ]
