# Generated by Django 5.2 on 2026-07-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_description_categoryattribute'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='categoryattribute',
            options={'ordering': ('sort_order', 'created_at')},
        ),
    ]
