# Generated by Django 5.2 on 2026-07-16 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('value', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('category_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.categoryattribute')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'constraints': [models.UniqueConstraint(fields=('category_attribute', 'value'), name='unique_value_per_attribute')],
            },
        ),
    ]
