# Generated by Django 5.2 on 2026-07-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_productreviewreport_shopreviewreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed by Admin')], default='PUBLISHED', max_length=20),
        ),
        migrations.AlterField(
            model_name='shopreview',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed by Admin')], default='PUBLISHED', max_length=20),
        ),
    ]
