# Generated by Django 5.2 on 2026-07-21 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_productreview_status_alter_shopreview_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productreviewreport',
            index=models.Index(fields=['review', 'is_resolved'], name='reviews_pro_review__10cac6_idx'),
        ),
        migrations.AddIndex(
            model_name='shopreviewreport',
            index=models.Index(fields=['review', 'is_resolved'], name='reviews_sho_review__7d3560_idx'),
        ),
    ]
